ams = [
"in short , i can say for certain that",
"to clarify ,",
"wherever possible ,",
"in my opinion , i agree with the second idea that",
"striking contrast ,",
"to give an example ,",
"some people believe that",
"first and foremost reason is that",
"inevitably ,",
"i think that a",
"they opine that",
"on the other hand , there are some people think that",
"in this essay , the reasons for why i agree that",
"for me",
"therefore , we can commence to agree that",
"i do n't deny that",
"despite of the above arguments , i still strongly believe that",
"i personally believe that",
"so , this example makes it obvious that",
"because ,",
", it should be emphasized that",
"i personally suppose that",
"to summarize , i strongly agree that",
"to wrap it all up ,",
"secondly , parents and schools should give priority on directing their kids about handwriting as",
"but i believe this is not the issue because",
"from my personal experience i recall that",
"nonetheless ,",
"however , as the society grows , human rights become more highly respected ,",
"above all ,",
"it is needless to say that",
"i believe that the",
"but on other hand ,",
"i personally believe that even when",
"at a higher level ,",
"those who disagree , believe that",
"but these young people do not take into account that",
"in conclusion , i reckon that",
"however",
"so i suggest",
"this seems to be easy but",
"on top of that ,",
"it is clear to recognize that",
"instead ,",
"because of the similarity i talked before ,",
"on one hand , i agree that",
"at least ,",
"to put it in a nutshell , the suggestion of",
"as hence",
", for me ,",
"for the above reasons , i agree that",
"in conclusion , the above stated reasons clearly outweigh the fact that",
"the soaring crime rate has led to the proposal that",
"as for the two integral components within the system , elementary and advanced education , there 's no doubt that a",
"in conclusion , my point of view is that , although",
"the main advantage is that",
", it is my belief that",
"in conclusion , i believe",
"first of all , some people claim that",
"lastly ,",
"hence , from this case , we are capable of stating that",
"for example , as we know ,",
"another issue is that in the ever - accelerated updating of science and technology ,",
"to sum up , it is clear that",
"taking into account of all these factors , we may reach the conclusion that",
"although some people argue that",
"to sum up , it makes no difference , people from young ages to old ages are free to make a decision , nonetheless sometimes to prevent some problems coming up for young individuals ,",
"from my point of view ,",
"what is worse ,",
"nevertheless , while i admit that",
"in my opinion ,",
"while i agree this will bring negative impacts on the younger generation ,",
"specifically ,",
"in terms of ethics ,",
"or , under many circumstances ,",
"by doing this ,",
"hence",
"next ,",
"first of all , it is true that",
"by way of conclusion , i once again restate my position that",
"from this example , it is obvious that",
"firstly ,",
"as far as i am concerned , i agree with that",
"on one hand ,",
"considering all the benefits ,",
"finally",
"thus , it is clear that",
"so that ,",
"relatively ,",
"in addition to this ,",
"it is not surprised that",
"i would maintain that",
", i claim that",
", but ,",
"first of all , it seems to be true that",
"while some people believe that",
"i always believe that a",
"there are many advantages of distance learning , but",
"adding to that ,",
"in conclusion , i personally agree with that",
"still ,",
"first of all",
"first of all , one of the most significant upsides is that",
"in conclusion , i totally believe that",
"while i accept that job can offer happiness to some people , i believe that",
"this is to say ,",
"besides the methods , from my point of view ,",
"in this case , i advocate the idea that",
", i completely argue that",
"besides , it is undeniable that",
"as a result",
"so , for example",
"for another ,",
"in short ,",
"i found that",
"in the first instance ,",
"firstly , i think that",
"according to the discuss above ,",
"however , from my perspective , i think",
"thus , i firmly believe that",
"alternatively ,",
"secondly , it is believed that",
"in a larger sense ,",
"there is no denying that",
"so the truth lies somewhere closer to the fact that a",
"to sum up , even when",
"considering this fact ,",
"in this condition , because",
"on the other hand , some people maintain that",
"to start ,",
"in conclusion , i feel certain that",
"and",
"most of the time ,",
"after analyzing smoke illegalization in public places in sri lanka ,",
"as we know ,",
"while most scientists claim that this is vital for improving human health , i believe that",
"for those reasons ,",
"thus , i would conclude that",
"in my opinion , there is a likelihood that",
"thirdly , i totally believe",
"nevertheless , opponents of modern communications claim that only",
"in my opinion , one of the main reasons for supporting this statement is that",
"in addition to that ,",
"in conclusion , from my point of view ,",
"however , i tend to believe",
"therefore ,",
"in my opinion , i agree that",
"in paticular ,",
"therefore , i believe",
"and in present ,",
"under this circumstance ,",
"in their opinion ,",
"moreover , the proponents of globalization idea point out",
"thus , in my point of view , although",
"but to me ,",
"in conclusion , even though",
"in my personal point of view ,",
"although some people claim that the advantages of advertising are outweigh the advantages , i believe that",
"however , i believe that",
"nonetheless , looking from another perspective ,",
"hence , i think",
"some people think that",
"in conclusion , after analysing the effects of world games both for countries at war and for organising countries ,",
"since ,",
"another point that should be taken into account is",
"or ,",
"from my perspective , i think",
"i mean ,",
"meanwhile , due to the fact that",
"in conclusion , in spite of some negative effects ,",
"without doubt ,",
"in addition , i believe that",
"in conclusion , i think that",
"as an example ,",
"to sum up , i think",
"in spite of bring fantastic advantages ,",
"from that",
"then ,",
"first and foremost , i believe that",
"the first reason is",
"apart from that ,",
"ultimately i feel that",
"as this shows ,",
"the main reason is that",
"first of all , there is no doubt that",
"despite this , it is undeniable that",
"even in some cases ,",
"it would be great if every zoo kept the animals in perfect conditions , but regardless of the condition ,",
"they further point out that",
"if i have to choose ,",
"to add up ,",
"besides , although",
"in conclusion , i admit that",
"together ,",
"firstly , the distinguishing fact of the",
"this , in turn ,",
"some people argue that",
"first , indeed",
"the third convincing reason is that",
"by considering this and being aware of that students have not any responsibility and other difficulty in comparison with a young man , we can infer that why",
"third , it is clear that",
"obviously",
"and therefore",
"as all of us know ,",
"but i tend to think that",
"; thus ,",
"nowaday ,",
"to sum up , i completely approve of the statement which says",
"nevertheless , with all the mentioned demerits ,",
"and consequently ,",
"because",
"this fortifies the fact that a",
"admittedly , on the other hands , there might be some dissidents proclaiming that",
"in actual ,",
", furthermore ,",
"with regard to the former ,",
"therefore , i will conclude that",
"in spite of many problems of having own business ,",
"first of all , although",
"it is widely thought that",
"then",
"so , i believe that",
"first , it is generally understood that",
"what 's even worse ,",
"accordingly ,",
"to sum thing up , i agree that",
", therefor",
"however , i strongly believe that",
"my personal view is that despite the emphasis of citizen safety ,",
"in my opinion , i strongly agree that",
"those activities have proven that",
"first , in my view",
"on the other hand , i believe",
"personally , i think",
"some opponents says that it is cruel to animals and nature , however , i believe that no sensible person will deny that",
"by way of conclusion , i believe that",
"in addition",
", so i think",
"eventually ,",
"it is clearly understood that",
"yet ,",
"despite the importance of working in team , i still believe that",
"when they know",
"to conclude , both options have their advantages , but personally i think",
"to sum up , it is evident for me that",
"in conclusion , i agree that",
"admittedly ,",
"due to the reasons given above ,",
", therefore",
"notable one of the shortcomings is that",
"in the meantime ,",
"on the one hand , it is clear that",
"recently , some people argue that",
"take myself for example ,",
"in conclusion , it is undeniable that",
"with this kind of power",
"as sport has become a common passion which passed over every national border ,",
"although there are some advantages to learning a foreign language in its original country , i firmly believe that",
"in conclusion , there is to say that , given the arguments above ,",
"it is true while",
"i completely agree with the idea that",
"but i believe that",
"to quote an instance ,",
"they argue that",
"but as far as i am concerned , i agree with the idea , which is that",
"in any case ,",
"i favor the former ; that is ,",
"for example , because",
"based on the reasons demonstrate above , i believe that",
"my view is that the",
"; however , i believe",
"on the other hand , i believe that",
"it is widely acknowledged that",
"instead",
"some people , however , still believe that they can exist for long time ; others disagree , arguing that",
"i m my opinion ,",
"even though",
"as the world 's situation is always changing ,",
"the message is",
"further more ,",
"futhermore ,",
"finally , i believe that",
"as far as i am concerned , i agree with the view that",
"however , some say that",
"as far as i am concerned , i think",
", thereby",
"on the one hand , i agree that a",
"some people claim that",
", to find that why",
"in the ways that",
"it is no doubt that the",
"from my point of view , i am in favor the former statement that",
"although multitudes of people think that knowledge of ideas and concepts is more vital for students , i am in the conviction that",
"taking everything into account , i strongly believe that",
"however , i am sure that",
"as such ,",
"however i strongly believe that",
", however ,",
"i favor the latter ; that is ,",
"however , from my perspective ,",
"on the other hand , it is no doubt that",
"by way of conclusion , it is true that",
"however , i agree that",
"; therefore , i believe",
"i agree with the statement that",
"this is because",
"to me ,",
"the first and foremost reason is that",
"regardless of some exceptions ,",
"finally ,",
"after careful consideration of both sides of the argument ,",
"secondly ,",
"in summary , even though",
"last but not least ,",
"i really believe that",
"undoubtedly ,",
"as you can see ,",
"it is true that",
"they argue that people ,",
"people who hold different opinion may argue that",
"despite all these positive aspects , i think that",
"another reason is that",
"in my views , i agree that",
"on other side of the coin , many people believe that",
"as a practical epitome ,",
", eating , etc . , but",
"however , to my mind",
"i belive this , due to the fact that",
"also ,",
"that 's not enough ,",
"frequently ,",
"after all ,",
"in my personal experience ,",
", i am inclined to believe that",
"therefore , i would conclude that a",
"in my personal opinion , i am totally agreed with the view that",
"in the same way ,",
"the long and the short of it ,",
"i agree that nowadays the learning process benefits greatly from computers , but",
"for this reason ,",
"secondly , students should not be required to attend classes because",
"in contrast ,",
"all in all ,",
"from my viewpoint ,",
"in a nutshell , varied characteristics of various people , feeling tired of having the same occupation and solving the unemployed problem drive me to agree with the statement that",
"as a fact that",
"this explains why",
"for instance",
"however , on the other side of the coin are voices in the opposition , saying that",
"as example",
", due to the fact that",
"nevertheless , it is undeniable that",
"all in all , from discussed reasons , we can conclude that",
"finally , beside all above mentioned items ,",
"first of all , i find the excitement of big cities to be attractive ,",
"it 's undeniable that",
"in such circumstances ,",
"on balance ,",
"in conclusion , though",
"although modern technology make it possible , i still believe",
"from reasons listed above , we can safely draw the conclusion that ,",
"although some people think that the major part of school schedule should be entirely devoted to academics , i truly believe that",
"to begin with , it is undeniable that",
"personally , i tend to agree with the point of view that",
"on the other hand , there are , however , people who think that",
"to be specific ,",
"there are people who believe that",
"however , despite the drawback mentioned above ,",
"despite the argument of some people that",
"individually ,",
"by which i mean ,",
"by contrast ,",
"also , i think",
"however , in my view ,",
"therefore in my view ,",
"most of all ,",
", i think they are wrong , since",
"is , primarily",
"to picture it ,",
"for another example ,",
", it is also true that",
"it is especially true if we consider the fact that a",
"therefore , it can be said that",
"collectively ,",
"to sumarize ,",
", for instance ,",
"taken all together ,",
"it is a matter of fact that",
"i would argue that",
"at times ,",
"apart from the one i have mentioned above , another equally important aspect is",
"however , as far as i am concerned , i strongly agree with the view that",
"however , according to my experiences ,",
", so i believe that",
"finally , i think that",
"last i want to mention is that even though",
"obviousness ,",
"firstly , it is an undeniable fact that",
"many employers argue that",
"many people find that",
"all in all , it is obvious that",
"in summary , although",
"in my personal opinion ,",
"to set another example ,",
"apart from saving a lot of money ,",
"however , from my point of view ,",
"at the end ,",
"i belive that",
"in conclusion , from the above views , although",
"meanwhile ,",
"so",
", and as a result ,",
"they think that",
"; so",
"to illustrate ,",
", but actually",
"according to a recent survey ,",
"based on the above discussion , i agree with that",
"for the above reasons and examples , it could be widely thought that",
"in conclusion as promising as renewable resources of energy sound ,",
"on the whole , i do believe that",
"nobody has a life with a lot of fun ;",
"in conclusion , it seems to me that",
"so ,",
"not to mention , that",
"besides that ,",
"thus , it is apparent that",
"during our trip ,",
"however , i am convinced that",
"thus , it is argued that",
"i strongly believe that",
"for these reasons ,",
"it can be said that",
"personally , i think that",
"finally , some assert that",
"it is clear that",
"however ,",
"i agree",
"i am totally convinced that",
"nevertheless , it is not unreasonable that some people think that",
"secondly , there are clear evidences that",
"another important point is that",
"to conclude this ,",
"furthermore ,",
"first , critics of zoology argue that",
"similarly ,",
"even so , i strongly believe that",
"to conclude ,",
"for instant ,",
"some people spot out that",
"another reason to fortify my opinion is that",
", since",
"besides ,",
"to sum up , i would like to say that for me both options of communicating are possible , but if this is an important and not urgent question",
"when it comes to the question whether classmates or colleagues should work on projects in person or by email , i am of the view that",
"one other important factor is",
"i agree with that idea that",
"i firmly believe that",
"all advantages considered ,",
"what is meant by this is that",
"but",
"it is widely known that",
"for instance ,",
"; in addition ,",
"in considering whether one should choose a job similar to his or her parents ' , i have mentioned a few reasons that",
"another reason ,",
"first of all , many of us would agree to the fact that",
"as a result of this ,",
"third , some parents are afraid that",
"hence , i agree with the majority , because",
"take an example ,",
"in conclusion ,",
"importantly ,",
"apparently",
"that 's why i believe that",
"although some people believe that students should spend the whole day on academic studies , i nevertheless believe that",
"some may argue that as time is different ,",
"this means , that",
"therefore , e",
"as studies have shown that",
"of course ,",
"according to this opinion ,",
", not to mention",
"finally , of course ,",
"in other word ,",
"increasingly however ,",
"concerning that",
"secondly , in my mind ,",
", so",
"thereafter ,",
"each year ,",
"today ,",
"what is more ,",
"however , i think",
"in this way ,",
"another reason why artists should be helped is because",
"for the reasons mentioned above ,",
"first of all , since",
"hence , it is clear that",
"with this situation , some people believe that",
"the first reason is that",
"of course",
"consequently , i think that",
"thereby",
"these are reasons that why",
"this is simply because",
"although",
"drive me to believe that",
"so that",
"however , the fact is that",
"the fact is that",
"it is also worth mentioning that",
", but we should also bear in mind that",
"another example is that",
"in conclusion , as a young women",
"from my point of view",
"in conclusion , i certainly can say that",
"hence , it is evident that",
"to begin with , i agree that",
"even",
", i support that",
"on the other hand",
"by contrast , some experts believe that",
"all in a nutshell ,",
"in spite of the fact",
"thus it is very obvious that",
"to put it all in a nutshell , i pen out saying that",
"environment ,",
"this issue is a controversial one , but in my opinion a closer examination reveals that",
"they point out that",
"to some extent ,",
"more importantly ,",
"moreover , it seems to me that",
"therefore , i agree that",
"from given the evidences , it seems to me that it becomes hard for students to choose between their living options since",
"nevertheless ,",
"in the other hand ,",
"in a word ,",
"i think that",
"in fact ,",
"in my viewpoint ,",
", and , furthermore ,",
"; thus",
"in conclusion , i admittedly and strongly agree that",
"the issue is controversial but in my opinion ,",
"in addition to the previous point ,",
"in conclusion , i completely agree that",
"i strongly disagree with this affirmation because i believe",
"furthermore",
"on the other hand there are people who say that",
"it is obvious that",
"but in fact ,",
"this is probably because",
"however , in my perspective ,",
"some people may argue that",
"i think , however ,",
", and this means that",
"ever since",
"after that i understood ,",
"taking all into account , i think that",
"in my opinion , however ,",
"to sum up , i would say that",
"third ,",
"in order to tackle the problem ,",
"another reason should be mentioned is that",
"the main reason for this issue is that",
"it is because",
"first and foremost ,",
"in conclusion , despite the contribution of it to the society ,",
"although miscellaneous people may apply diverse strategies , such as reading , watching movies , or working in their gardens , i argue that",
"however , as",
"the first reason why",
"in opposite ,",
"in summary ,",
"not only that ,",
"another supporting reason is that",
"i would not go along with their viewpoint as",
"therefore , in my opinion , i accede with notion that",
"there can be no doubt that",
", it is because",
"while some argue that the budget allocation to the arts is waste of national resources and the money should instead be spent on public services , i contend that",
"nevertheless , i think",
"it is out of of the questioned that",
"from then",
"overall , i believe that",
", thus ,",
"because of all the reasons mentioned above , namely",
"unfortunately",
"another function that",
"nowadays ,",
"needless to say ,",
"it is hard to judge which generation 's problems are more difficult but",
"the first and foremost reason lies in an inevitable fact that",
"this point has some merits on the surface ; however ,",
"admittedly , in concerning the social relationship with peers , some may support that",
"however , the other side of the coin is that ,",
"also",
"admittedly , to some extent ,",
"to conclude , although",
"however , despite the fact that",
"many people agree that",
"; while on the contrary ,",
"to sum up , i am strongly convinced that",
"first , as you can see that",
"instead of this ,",
"on top of this ,",
"in concluding ,",
"equally important ,",
"but ,",
"to sum up , i reaffirm that although",
"it ’s undisputed that",
"in spite of the importance of sports activities ,",
"this clearly shows that",
"in this view ,",
"however , in my opinion ,",
"actually ,",
"some people thinks that",
"as far as i am concerned , i agree with the opinion",
"as illustrated before ,",
"and thus",
"otherwise , another vital reason why",
"by way of conclusion , it is my belief that",
", while",
"i , for one ,",
"that is to say ,",
"i admit that",
"in the end ,",
"in my opinion though ,",
"many people hold the opinion that",
"the first important point that i want to make is that",
", for",
"this is due to the fact that ,",
", not only because",
"although it is true that",
"however , while",
"to sum up , i would maintain that",
"first of all , it is seen that",
"so obviously ,",
"we can see now that",
"from my prospect , i believe that",
"on the other hand , the advocators believe that",
"i think",
"all in all , i suppose that",
"in conclusion , i strongly believe that",
"however , in my point of view ,",
"some people might say i am silly , but i think",
"another point is that ,",
"although multitudes of people think that sports and social activities are not as necessary as academic subjects in colleges , i think that",
"for these reasons , i agree that",
"as a matter of fact ,",
"although i conceded",
"what 's more ,",
"after analyzing both points of view ,",
"in the first place , there is no doubt that",
"that is how ,",
"as can be seen from this , is that a",
"because of that ,",
"in my view ,",
"in conclusion , it is convincing that",
"another perspective ,",
"for the reasons mentioned above , i believe that",
"while critics castigating about the exorbitant use of oil and other insisting to charged drivers with extra fee during the rush hours for their selfish conducts , i hold the contention that",
"first of all , as i mentioned above",
"although there are good arguments in favour of this trend should be encouraged , i personally think that",
"because i strongly feel that",
"in the past few decades ,",
"as a token of goodwill ,",
"however , i still agree that",
"in conclusion , i agree with that",
"personally , i believe",
"responsible because",
"as a result , i believe that",
"beside ,",
"however , i strongly agree with that",
"it is my personal belief that",
"while some people might think that this international tourism has negative effects on the destination countries , i would contend that",
"to illustrate my point ,",
"; therefore ,",
"although it is real in some aspects , i believe that",
", but i strongly believe",
"as far as my opinion is concerned ,",
"however it is an obvious fact that",
"in the end , i think",
"i want to say that",
"as a lover of travel ,",
"instead , the real causes of traffic jam may fall on various of grounds , and therefore ,",
"however , some people might argue that",
"with those arguments in mind , i would conclude that",
"especially ,",
"thirdly , at some point ,",
"most important of all ,",
"in a nutshell , i am convinced that",
"another thing that put big cities in front of small towns is",
"in the contrary ,",
"and as a result",
"this is only partially true ,",
"even so ,",
"in conclusion , i am firmly supporting the view , that",
"in conclusion , i personally believe that",
"in this case ,",
"more specifically ,",
", thus",
", i certainly believe that",
"i have observed that",
"to be more specific ,",
"while some critics may argue that ,",
"many parents supporting for the idea of tax discounts claim that",
"that ’s why",
"in conclusion , while",
"secondary ,",
"in a nutshell , i believe that",
"truthfully ,",
"in these cases ,",
"to add to it ,",
"i however , agree to this only to a certain extent and believe that",
"as we all know ,",
"by the way ,",
"admittedly , on the other hand , there might be some dissidents proclaiming that",
"moreover , another equally crucial aspect is that",
"secondly , it is obvious that",
"apart from the one i have mentioned above , another equally crucible aspect is that",
"i agree with this opinion to some extent , but",
"for the above reasons , i believe that",
"i believe that",
"despite friendship is one of the most important values in a man 's life , people might have different preferences : some of them prefer to spend time with one or two close friends , while",
"for one ,",
"to sum up , i would have to say that although",
"in conclusion , of course ,",
"from my perspective , i agree with the view that",
"after having considered all the problems that i have discussed above , we can finally draw a conclusion that although",
"this is of paramount importance so that",
"the second reason why",
", also",
"for me , i believe",
"in a positive point of view ,",
"therefore this proves that",
"with the rapid developing pace ,",
"many people claim that",
"in facts ,",
"consequently ,",
"but we have to realize the fact :",
"to cite an example ,",
"time and again ,",
"looking from another perspective ,",
"this example shows that",
"all in all , that",
"all in all , i agree that",
"that is because ,",
"the history shows that",
"all thing considered ,",
"first and foremost , i truly believe that",
", what 's more ,",
"simply put ,",
"by considering all reasons ,",
"while",
"as for me ,",
"at this moment ,",
"critics may argue that",
"from all analysis suggested above ,",
"on the basis of the points mentioned above , i convinced that",
"from my perspective ,",
"nonetheless , i believe that",
"it is generally believed that ,",
"no doubt ,",
"to conclude , i definitely feel that",
"for",
"alike ,",
"if students want to get used to the society quickly ,",
"in another word ,",
"these examples make it obvious that",
"to sum up , i admire my father 's choice , while",
", i think",
"the other reason is that",
"in this sense ,",
"in conclusion , i firmly believe that",
"therefore , i would conclude that",
"to be precise , for instance ,",
"in conclusion , i would concede that",
"obviously ,",
"the outcome is that",
"some people think that a",
", that 's why",
"averagely ,",
"although some argue that a",
"from this experience , i believe that a",
"from my point of view , i believe that",
"futuermore ,",
"second , i think that a",
"to begin with , the major cause that leads to urban migration of young adults is that",
"for example",
"other people say that",
", i firmly object to it because",
"; also ,",
"apart from this ,",
"besides easing tensions ,",
"following both the point of views ,",
"in tradition ,",
"second ,",
"lastly , the most important reason i support this idea is",
"in this case , i would definitely agree that",
"one benefit is that",
"the first reason why people are willing to visit museums when they travel to a new territory is that",
"to conclude , i want to say that",
"also , it is obvious that ,",
"here is an example :",
"secondly , even though",
"however , despite the advantages of small town life ,",
"admittedly",
"as",
"in conclusion , although",
"as a consequence ,",
"the reason is that",
"indeed ,",
"in order to solve the education manpower problem ,",
"finally , although",
"in other words ,",
"although i accept that students have to study many subjects in school ,",
", and as a result",
"we can not deny that",
"further ,",
"in general ,",
"furthermore , even though some customers do not worry about the threat that second - hand smoke imposes on them ,",
"however , the opponents believe that",
"to sum up ,",
"to begin with ,",
"since",
"in addition to controlling emission carbon dioxide ,",
"on the contrary ,",
"therefore , to conclude my opinion on this statement , i want to mentioned that",
"it is obvious axiomatic that",
"personally , i believe that",
"on the other side ,",
"to sum it up , from above mentioned facts it can easily be deduced that",
"from the point of the local community ,",
"nevertheless , opponents of online - degrees would argue that",
"to some extent , i do not agree with this assertion because i believe that",
"consequently , no matter from the view of individual development or the relationship between competition and cooperation we can receive the same conclusion that a",
"by doing so ,",
"the result shows that",
"we must acknowledge that",
"hence it is always said that",
", so that",
"little wonder , then , that",
"first , it 's true",
"but like i said ,",
"other than that ,",
"last but not least , nowadays ,",
"that is ,",
"from another point of view ,",
"as the impacts for those pollution and traffic issues are extremely far - reaching ,",
"worse still ,",
"in conclusion , i strongly agree that",
"my opinion based on the reasons that every tough",
"at the same time ,",
"on the one hand ,",
"for another thing ,",
"this means that the",
"as i have said ,",
"admittedly , opponents may blame that",
"to conclude , as far as i am concerned ,",
"however , in order to tackle this problem more effectively ,",
", i would contend that",
"on the whole ,",
"in conclusion , i agree with this statement that",
"hence , from this case we are capable of stating that",
"in the second place ,",
"in my opinion",
"however , because",
", because",
"generally speaking , i definitely agree with the statement that",
"initially , if we look into the fact ,",
"in the conclusion , i would like to say that",
"in the event of an argument ,",
", and to achieve this ,",
"despite the fact that",
"thus this makes it clear that",
"it is believed that",
"everyone agrees that",
"there are few of those who are concerned think the current practice should be altered and that",
"nevertheless , i feel that",
"i will establish my view by analysing how",
"certainly",
"as far as i am concerned , i strongly believe that",
"nowadays , more and more people begin to select prepared food as their daily meals , since",
"however , i would argue that",
"in addition , although",
"the best example is",
"clearly ,",
"they may say that",
"there are several reasons why",
"therefore , i believe that",
"some people claim",
"through this way ,",
"in this regard",
"it is a debatable subject that",
"another significant factor of universities is that",
"fortunately ,",
"not only because",
"because , at least for him ,",
"from this ,",
"last ,",
"based on these grounds , it seems that",
"based on the reasons demonstrated above ,",
"first of all , as we all know ,",
"thus",
"this means that",
"thus , i strongly believe",
"on the other hand , some people oppose the argument , saying",
"in order to protect animals , from my perspective ,",
"i absolutely agree that",
"that ’s as important thing because",
", even though",
"finally yet importantly ,",
"for the same reason ,",
"some people say :",
"it is undeniable that",
"at this point ,",
"furthermore / moreover ,",
", i firmly believe that",
"especially",
"to be precise ,",
"however , someone may maintain that",
", and",
"therefore , to make use of time ,",
"for the above - mentioned reasons ,",
", therefore ,",
"firstly , the reason why university students should not be required to attend class is",
"some",
"on most occasions ,",
"those who advocate focusing on one subject believe that",
"having said that",
"in my opinion , i believe",
"this is because ,",
"secondly",
"in sum ,",
"the reason why most people oppose to zoos is that",
"personally ,",
"admittedly , on the other hand , there might be some people proclaiming that",
"by way of conclusion , i do not root for the idea that restrictions should be put on artists work ; on the contrary ,",
"this means ,",
"in order to solve these problems ,",
", although",
"in sum , though some people may disagree with me , as i explained my reasons and examples above , none of those factors are important and sufficient enough by themselves and",
"that 's why",
"due to this neglect ,",
"it is undoubted that",
", like my mom , i still hold the firm view that",
"it is sure that",
"the best choice is obviously stand on my side , which is that a",
"to conclude , i believe",
"another reason that makes learning by doing things more advantageous than learning by reading about things or listening to people talking about is that",
"to my view , i incline to believe",
"every day ,",
"to sum up , i believe that a",
"but from my experience ,",
"central to the supporting arguments of this issue is the idea that",
"second , i think",
"nevertheless , there are some other causes why",
"nevertheless , i assert that",
"though",
"to illustrate this further ,",
"few individuals assume that",
"and i believe",
"all in all , i am in the conviction that",
"moreover",
"for this point , they all think that",
"thus , i think",
"in my experience ,",
"due to the fact that",
"there is no doubt that",
"in conclusion , i strongly hold my point that",
"in light of the above - mentioned facts , one can easily conclude that",
"because of",
"although ,",
"to solve these issues ,",
"; moreover ,",
"to start with ,",
"so , from what have been discussed above , i strongly affirm the conclusion that",
"due to",
", in my opinion",
"economically speaking ,",
"that 's the main reason",
"most importantly ,",
"the first and foremost reason lies in the inevitable fact that",
", nevertheless",
"first of all , i do support the idea that",
"first of all , many people think that",
"as you can imagine ,",
", but also",
"another reason is that ,",
"unfortunately ,",
"all things considered ,",
"first , i think",
"primary ,",
"after analyzing these two points of view , it is believed that",
"personally i think ,",
"i agree with both opinions that",
"nevertheless , for the reasons that i have presented above ,",
"however , i would contend that",
"thirdly ,",
"nevertheless , i believe that",
"hence , from this case ,",
"as we can see",
"additionally ,",
"in addition to what mentioned ,",
"therefore",
"according to my opinion , because",
"because not only do",
"those who feel that",
"to sum up , although",
"as a result ,",
"many people believe that",
"for the primary concern ,",
", and accordingly ,",
", but i think",
"in conclusion , due to the fact that",
"to make it convenient ,",
"nevertheless , since",
"yet because",
"now that ,",
"to put it in a nutshell , i pen down saying that ,",
"although some people argue these developments are making our life comfortable , but",
"totally ,",
"that",
"from their point of view , the fact is that",
"despite the importance of helping those beyond our national borders ,",
"in this context ,",
"as far as i am concerned , i agree with the statement that",
"it is felt by many that",
"plus",
"as you see ,",
"to begin with , in schools ,",
", possibly because",
"i agree to the argument that",
"although many people prefer communicating by telephone or face - to - face , personally i believe that",
"firstly , it is undoubtedly that",
"however , i do think that",
"in fact",
"simultaneously ,",
"following the demonstration of a computer 's contribution in children 's study and building skills which are to be used in their career afterwards , it is agreed that",
"although both companies have their advantages and disadvantages ,",
"however , i am utterly convinced that",
"for me ,",
"i agree that",
"this example makes it clear that",
"lies in the fact that",
"they believe that",
"this argument may be true that",
"and finally ,",
"given these evidences , it can be seen that",
"it is clear to me that",
"as a conclusion , i personally think that",
"in sum , sometimes",
"undoubtedly",
"some people who hold different viewpoints may advocate that",
"for the above reasons ,",
"in a nutshell ,",
"to conclude , i would say that",
"in a word , although each of these methods have their pros and cons , i am pretty sure that",
"at the second point ,",
"to sum up , in spite of the fact that",
"first of all , the ancient latin proverb says : ' anima sana in corpore sano ' , which means that",
"to begin with , it is vital that",
"it seems that",
"because of that need ,",
"the reason for this is",
"to my mind ,",
", but in my own view ,",
"and then",
"the reason is that ,",
"nevertheless , i agree to this solution only to a certain degree because i feel that",
"for example ,",
"but i think",
"along with that ,",
"therefore , we can start to agree that",
"as well as",
"whereas ,",
"after considering the level of freedom , the studying conditions and the economic factor , if i had to choose ,",
"at first ,",
"therefore , i agree with this notion that",
"there is no deny that",
"in addition , the learning with a teacher makes us bear more burdens of studies cause they assign us homework , nevertheless ,",
"basically ,",
"it is certainly clear that",
"moreover , i have always believed that",
"one reason is that",
"thus ,",
", firmly believe that",
"to clarify my point i would like to say a memory from my childhood ,",
"i am a kind of person who believes to",
"to summarize ,",
"even though the purposes could be various ,",
"; therefore",
"however , i believe ,",
"it was said that",
"despite the convenience from up - to - date facilities ,",
"in my point of view , though",
"all in all , i am in the belief that",
"this is understandable",
"first ,",
"besides , it is obvious that",
", it is convincing that",
"all in all , i would maintain that",
"in condition ,",
"first of all ,",
"to conclude , no matter how fast and convenient modern devices bring to us in writing ,",
"based on the reasons demonstrated above , i believe that",
"in conclusion , it is my belief that",
"from this point of view , i firmly believe that",
"in the sense that",
"apparently ,",
"if you have a great love with football and your home team ,",
"in conclusion , i can certainly state that",
"in conclusion , after analyzing the pros and cons of advertising , both of the views have strong support , but it is felt that",
"interestingly ,",
"hence ,",
"except these ,",
"i believe",
"as it can be seen from the example ,",
"and as result ,",
", nevertheless ,",
"some people say that",
"first of all , it is recognized that",
"thus , i believe that",
", i can not help but assure that this is a matter of personal taste , to be clear ,",
"so i think",
"in result",
"however , even with all the conveniences , we would have to admit that",
"in short , although both sides have their equally valid arguments , i am inclined to think that although",
"however , we should bear in mind that",
"at this circumstances ,",
"nevertheless , supporters would argue that",
"as evidence of this ,",
"in conclusion , despite the fact that",
"in conclusion , in my view",
"clearly , although",
"in conclusion , i personally agree with statement that",
"overemphasizing on personal lives of famous people by media as a mass media majoring student , i think that it 's true that",
"people who hold different opinion may argue that a",
"further and even more importantly ,",
"ultimately ,",
", but i think that",
"from my point of view although",
"for example :",
"automatically ,",
", but",
"should be encouraged , i personally think that",
"although renewable resources of energy are elements of the current and future energy strategy , as far as i 'm concerned , these",
"in conclusion , i believe that",
", but on the other hand",
"furthermore , it 's undeniable that the",
"based on my arguments above , i think",
"that is the reason why",
"in the past time ,",
", too , but i imagine",
", i would state that",
"from the discussed above , we can easily draw the conclusion that",
"therefore , it seems that",
"after that ,",
"considering all those factors above ,",
"the reason why i think",
", it seem to me that",
"the fact that",
"therefore , here goes the point that",
"i completely agree that",
"as a case in point ,",
"in sum , i believe that",
"animal protectionists may base their argument on the ground that",
"another important thing to consider is that",
"in conclusion , given the reasons described above , when the advantages and disadvantages of whether there will be fewer cars in use in twenty years or not are carefully compared , the best choice is obviously stand on my side , which is that",
", for example ,",
"in such case ,",
"in my view , i agree to that fact that",
"considering all the above mentioned arguments , from my point of view",
"if someday i have children , i ’m absolutely sure that",
"while some might think",
"as the example above indicates ,",
"although those above reasons are acceptable , i would argue that",
"unlike classroom ,",
"however , i am inclined to believe that",
"in the first place ,",
"while both positions seem reasonable , my view is that ,",
"in conclusion , i would argue that",
"overall ,",
"second of all ,",
"in my opinion , i agree with the latter because",
"in conclusion , i concede that",
"i confess that",
"in my opinion , i think",
"as for the latter point ,",
"an even more detrimental fact is that",
"despite these problems , personally ,",
"based on the factors i have mentioned above , a conclusion can be drawn that although",
"it is agreed that",
"it does not seem unreasonable to suggest that",
"initially ,",
"this saying is stating that",
"in the near future ,",
"in my point of view ,",
"in result ,",
"in our hectic life , however ,",
"to conclude , i strongly believe that",
"in conclusion , as i believe that consumers should consider major needs when they purchase goods ,",
"i do believe that",
"i support the points of those who say that",
"last , but not least ,",
"in conclusion , i strongly agree with notion that",
"firstly , some people suggest that",
"in a nutshell , although",
"therefore i strongly agree with the argument that",
"alternatively i believe that",
"in other words , i think",
"ergo ,",
"some people might argue that",
"and hence",
"another significant fact which should be taken into consideration is that",
"this is an important factor because",
"in conclusion , i strongly feel that",
"what 's worse ,",
"the consequence of this case made",
"on the other hand ,",
"as we all know",
"while mother 's role is essential in a child 's life , i completely agree with the idea that",
"something else that is good is that",
"another reason is that a",
"primarily ,",
"to give a brief conclusion ,",
"as far as i am concerned ,",
"on the whole , to compare to all ways of communication , i really think that",
"therefore , i strongly agree that",
"generally , personally speaking , i believe",
"i have an impression that",
"in my opinion , i believe that",
"from my prospective ,",
"moreover ,",
"it is a well - known fact that",
"thus to conclude , it can be said that",
"it is widely seen that",
"i also believe",
"in addition , because",
"to conclude , it is now evident that",
"this means",
"however , i believe",
"personally speaking ,",
"in my opinion , though",
"; however ,",
"as a rule of thumb ,",
", so their",
"for them ,",
", as",
", hence",
"for one thing ,",
"to start with , since",
"otherwise ,",
", but i agree that",
"more ,",
"in my view point ,",
"this will be proven by analyzing how",
"the main reason why i believe artists should be funded is because",
"in sum , although each choice - few close friends or a large number of friends - presents its advantages and its weak points , i think that",
"in addition ,",
"while there is belief that technology advances means a lost in traditional cultures , i would argue that although",
"second , from an economic point of view , people often argue that",
"in conclusion , while there",
"one can not deny the fact that",
"it is certainly true that",
"my view is that",
"and i think",
"in conclusion , i think",
"in my perspective ,",
"they will argue ,",
"; consequently ,",
"with the economy development ,",
"mentioned to societies life style ,",
"i totally agree that",
"personally , i do not agree the viewpoint , because",
"in coclusion ,",
"so , i definitely believe that",
"i am biased towards the opposite side that",
]